# Generated by Django 3.2.16 on 2022-12-26 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='ID')),
                ('userPassword', models.CharField(max_length=255)),
                ('userName', models.CharField(max_length=255)),
            ],
        ),
    ]
