# Generated by Django 3.2.16 on 2022-12-26 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djblth', '0002_auto_20221226_1049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctorId', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctorPassword', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('doctorName', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('doctorPatients', models.JSONField()),
            ],
        ),
    ]
